package constants

// log_templates.go 集中定义全部日志格式字符串（≥25 条），handler/service/middleware 必须引用。
const (
	LOG_SERVER_STARTED             = "server started"
	LOG_SERVER_SHUTDOWN            = "server shutdown"
	LOG_DB_INITIALIZED             = "database initialized"
	LOG_CLIENT_CREATED             = "ApiClient created"
	LOG_CLIENT_UPDATED             = "ApiClient updated"
	LOG_CLIENT_STATUS_CHANGED      = "ApiClient status changed"
	LOG_CLIENT_TOKEN_ISSUED        = "ApiClient token issued"
	LOG_CLIENT_TOKEN_FAILED        = "ApiClient token issue failed"
	LOG_API_KEY_VERIFY_FAILED      = "ApiKey verify failed"
	LOG_INSURED_VERIFY_START       = "InsuredPerson verify start"
	LOG_INSURED_VERIFY_SUCCESS     = "InsuredPerson verify success"
	LOG_INSURED_VERIFY_FAILED      = "InsuredPerson verify failed"
	LOG_FEE_UPLOAD_START           = "FeeItem upload start"
	LOG_FEE_UPLOAD_VALIDATED       = "FeeItem upload validated"
	LOG_FEE_UPLOAD_DUPLICATE       = "FeeItem upload duplicate"
	LOG_FEE_UPLOAD_FAILED          = "FeeItem upload failed"
	LOG_PRESETTLEMENT_CALCULATED   = "Presettlement calculated"
	LOG_PRESETTLEMENT_FAILED       = "Presettlement calculation failed"
	LOG_SETTLEMENT_SUBMITTED       = "SettlementOrder submitted"
	LOG_SETTLEMENT_FAILED          = "SettlementOrder submit failed"
	LOG_SETTLEMENT_REVERSED        = "SettlementOrder reversed"
	LOG_SETTLEMENT_REVERSE_FAILED  = "SettlementOrder reverse failed"
	LOG_RECONCILIATION_GENERATED   = "DailyReconciliation generated"
	LOG_RECONCILIATION_FAILED      = "DailyReconciliation generation failed"
	LOG_AUDIT_WRITTEN              = "AuditLog written"
	LOG_RATE_LIMITED               = "request rate limited"
	LOG_REQUEST_START              = "request start"
	LOG_REQUEST_FINISH             = "request finish"
	LOG_PANIC_RECOVERED            = "panic recovered"
	LOG_BATCH_NO_GENERATED         = "UploadBatch batch_no generated"
	LOG_SETTLEMENT_NO_GENERATED    = "SettlementOrder settlement_no generated"
)
